# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tango',
                'doc_host': 'https://sandbox-ai.github.io',
                'git_url': 'https://github.com/sandbox-ai/tango',
                'lib_path': 'tango'},
  'syms': { 'tango.core': {'tango.core.foo': ('zz_template.html#foo', 'tango/core.py')},
            'tango.doc': { 'tango.doc.foo': ('designdo2cc.html#foo', 'tango/doc.py'),
                           'tango.doc.hello': ('designdo2cc.html#hello', 'tango/doc.py')},
            'tango.template': {'tango.template.foo': ('zz_template.html#foo', 'tango/template.py')}}}
