"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_designDo2cc.ipynb.

# %% auto 0
__all__ = ['foo', 'hello']

# %% ../nbs/01_designDo2cc.ipynb 3
def foo(): pass

# %% ../nbs/01_designDo2cc.ipynb 6
def hello():
    print("hello")
